"""add_skills_column_to_characters

Revision ID: 01b111d5ae14
Revises: 8ca0080ceb47
Create Date: 2026-02-06 15:12:27.734927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01b111d5ae14'
down_revision: Union[str, None] = '8ca0080ceb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_characters', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_characters', 'skills')
    # ### end Alembic commands ###
