"""add_ai_characters_and_character_images

Revision ID: 8ca0080ceb47
Revises: 62721613f103
Create Date: 2026-02-05 14:32:26.324005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ca0080ceb47'
down_revision: Union[str, None] = '62721613f103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mbti', sa.String(length=4), nullable=True),
    sa.Column('political_leaning', sa.String(length=50), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('familiarity_level', sa.Integer(), nullable=False),
    sa.Column('avatar_prompt', sa.Text(), nullable=True),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_characters_user_id'), 'ai_characters', ['user_id'], unique=False)
    op.create_table('character_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('is_avatar', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['ai_characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_images_character_id'), 'character_images', ['character_id'], unique=False)
    op.add_column('conversation_logs', sa.Column('character_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_conversation_logs_character_id'), 'conversation_logs', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_logs_character_id'), table_name='conversation_logs')
    op.drop_column('conversation_logs', 'character_id')
    op.drop_index(op.f('ix_character_images_character_id'), table_name='character_images')
    op.drop_table('character_images')
    op.drop_index(op.f('ix_ai_characters_user_id'), table_name='ai_characters')
    op.drop_table('ai_characters')
    # ### end Alembic commands ###
